site_name: garnet技术笔记
nav:
  - Home: index.md
  - 杂谈:
      - 快速搭建技术博客: 杂谈/快速搭建技术博客.md
  - cpp:
     - 基本概念: cpp/基本概念.md


markdown_extensions:
  - markdown.extensions.codehilite
  - markdown.extensions.extra
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.tables

theme:
  # name: readthedocs
  name: material



extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
