site_name: garnet技术笔记
nav:
  - Home: index.md
  - 杂谈:
      - 快速搭建技术博客: 杂谈/快速搭建技术博客.md
  - cpp:
     - 基本概念: cpp/基本概念.md


markdown_extensions:
  - markdown.extensions.codehilite
  - markdown.extensions.extra
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.tables
  - toc:
      permalink: true       # 在每个标题旁添加链接
      toc_depth: 1-3        # 只包含 h1 到 h3 的标题


theme:
  # name: readthedocs
  name: material
  palette:
    primary: 'indigo'       # 主颜色
    accent: 'pink'          # 强调颜色
  font:
    text: 'Roboto'          # 主文字字体
    code: 'Roboto Mono'     # 代码块字体
  features:
    - navigation.tabs       # 顶部标签
    - navigation.indexes    # 对于包含子页面的节，提供更好的索引页面
    - navigation.sections   # 结构化分节
    - navigation.instant    # 即时导航
    - toc.integrate         # 目录整合到侧边栏
    - palette.switcher      # 主题色切换
    - search.suggest        # 搜索建议
    - search.highlight      # 搜索关键词高亮
    - instant.loading       # 启用页面的即时加载



extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
