site_name: garnet技术笔记
nav:
  - Home: index.md
  - 杂谈:
      - 快速搭建技术博客: 杂谈/快速搭建技术博客.md
      - 批量下载与合并课件: 杂谈/批量下载与合并课件.md
      - inkscape去矢量图白边: 杂谈/inkscape去矢量图白边.md
  - Linux:
      - terminal_快捷键以及配置: Linux/terminal_快捷键以及配置.md
      - vim_使用nvim: Linux/vim_使用nvim.md
      - 非管理员权限安装htop: Linux/非管理员权限安装htop.md
      - vim_强制tab对应4空格: Linux/vim_强制tab对应4空格.md
      - 集群_mpirun报错: Linux/集群_mpirun报错.md
  - math:
    - Mathematica速查: math/MathematicaCheatsheet.md
  - FEM:
    - 科学计算准则与协议: FEM/科学计算准则与协议.md
  - latex:
    - cheatsheet: latex/cheatsheet.md
    - 修改 bibtex 参考文献格式: latex/修改 bibtex 参考文献格式.md
    - 本地与在线overleaf区别: latex/本地与在线overleaf区别.md
  - python:
      - pdb: python/pdb.md
      - python无法支持汉字: python/python无法支持汉字.md
  - cpp:
     - 基本概念_基础类型_操作符: cpp/基本概念_基础类型_操作符.md
     - 基本概念_enum_struct_控制流: cpp/基本概念_enum_struct_控制流.md
     - 基本概念_指针: cpp/基本概念_指针.md
     - 基本概念_函数_预处理: cpp/基本概念_函数_预处理.md
     - 面向对象编程: cpp/OOP.md
     - 模板元编程: cpp/模板元编程.md
     - 翻译单元: cpp/翻译单元.md
     - 编程规范: cpp/编程规范.md

     



markdown_extensions:
  - attr_list
  - md_in_html  # https://squidfunk.github.io/mkdocs-material/reference/images/
  - markdown.extensions.codehilite
  - markdown.extensions.extra
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.tables
  - toc:
      permalink: true       # 在每个标题旁添加链接
      toc_depth: 1-6

plugins:
  - mkdocs-pdf

theme:
  # name: readthedocs
  name: material
  custom_dir: overrides
  palette:
    primary: 'indigo'       # 主颜色
    accent: 'pink'          # 强调颜色
  font:
    text: 'Roboto'          # 主文字字体
    code: 'Roboto Mono'     # 代码块字体
  features:
    - navigation.indexes    # 对于包含子页面的节，提供更好的索引页面
    - navigation.instant
    - navigation.path       # 在文档顶部也显示当前文档的 
    - navigation.top
    - navigation.tabs
    - palette.switcher      # 主题色切换
    - search.suggest        # 搜索建议
    - search.highlight      # 搜索关键词高亮
    - instant.loading       # 启用页面的即时加载
    - navigation.footer



extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  # - javascripts/extra.js

extra:
  analytics:
    provider: google
    property: G-Y1TF9T1LW8
