site_name: garnet技术笔记
nav:
  - Home: index.md
  - 杂谈:
      - 快速搭建技术博客: 杂谈/快速搭建技术博客.md
  - cpp:
     - 基本概念: cpp/基本概念.md


markdown_extensions:
  - markdown.extensions.codehilite
  - markdown.extensions.extra
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.tables
  - toc:
      permalink: true       # 在每个标题旁添加链接
      baselevel: 1          # 从 h1 开始
      toc_depth: 2-3        # 只包含 h2 到 h3 的标题


theme:
  # name: readthedocs
  name: material
  features:
    - navigation.tabs   
    - navigation.top   
    - navigation.sections
    - navigation.instant
    - toc.integrate      # 确保目录被整合到侧边栏



extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
